### ISSUE TITLE
Scalastyle cannot handle trailing commas

### ISSUE THREAD

**Issue by cstroe** [olisikh/gradle-scalastyle-plugin#13]
Scala introduced trailing comma support in [2.12.2](https://github.com/scala/scala/releases/tag/v2.12.2) (see [SIP-27](https://docs.scala-lang.org/sips/trailing-commas.html)).

However, it seems that Scalastyle does not currently support this new syntax.  I've created a [sample project to show the bug](https://github.com/cstroe/gradle-scalastyle-plugin-test-project/blob/master/src/main/scala/cloud/cosmin/scalastyle/bug/MyClass.scala#L7):

```
⟩ ./gradlew scalastyleCheck

> Task :scalastyleMainCheck FAILED
error file=/Users/cstroe/Workspace-20Percent/gradle-scalastyle-plugin-test-project/src/main/scala/cloud/cosmin/scalastyle/bug/MyClass.scala message=illegal start of simple expression: Token(RPAREN,),101,))
Processed 1 file(s)
Found 1 errors
Found 0 warnings
Finished in 624 ms
```

**UPDATE:** It seems like this is captured as an issue with Scalastyle: https://github.com/scalastyle/scalastyle/issues/276

**Comment by cstroe** [comment]
Seems like someone forked Scalastyle because the original project is not maintained: https://github.com/scalastyle/scalastyle/issues/327#issuecomment-531173988

**Comment by olisikh** [comment]
Hi,

Yes, there’s a problem with trailing commas that is very annoying.
However this problem should be fixed on scalastyle project because this plugin is only a runner for scalastyle that is an external jar dependency.

**Comment by olisikh** [comment]
Closing as this is a bug of a scalastyle itself.
