### ISSUE TITLE
The published gradle plugin is an old version

### ISSUE THREAD

**Issue by tomyy** [olisikh/gradle-scalastyle-plugin#19]
I just integrated the gradle-scalastyle-plugin 3.2.0 into one of my projects.

However, if I configure the scalastyle plugin with

```
scalastyle {
    scalaVersion = '2.13'
    scalastyleVersion = '1.3.0'
}
```
the scalastyleCheck task fails with
```
Execution failed for task ':scalastyleMainCheck'.
> Could not resolve all files for configuration ':scalastyle'.
   > Could not find org.scalastyle:scalastyle_2.13:1.3.0.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/scalastyle/scalastyle_2.13/1.3.0/scalastyle_2.13-1.3.0.pom
 ```
So the plugin obviously still tries to load the old scalastyle jars.

It can work around the problem by using the following configuration instead:

```
scalastyle {
    // scalaVersion = '2.13'
    // scalastyleVersion = '1.3.0'
}
dependencies {
    scalastyle 'com.beautiful-scala:scalastyle_2.13:1.3.0'
    // other dependencies
}
```

**Comment by olisikh** [comment]
Hi @tomyy,

Thanks for sharing this issue.
Indeed, the last released plugin jar is broken 🤦‍♂ 

Please check out 3.3.0, should be fixed there.

**Comment by tomyy** [comment]
Hi @alisiikh,

Thanks for the prompt response.
I verified that the latest release 3.3.0 fixes the problem.
