### ISSUE TITLE
The 'scalaStyleCheck` task does not automatically make the `check` task depend on it

### ISSUE THREAD

**Issue by Flowdalic** [olisikh/gradle-scalastyle-plugin#4]
The `scalaStyleCheck` task does not automatically make the `check` task depend on it. This is unexpected as normally gradle check/test type plugins automatically make the generic check/test task depend on them so that they are always run (if not explicitly disabled). The official gradle checkstyle plugin does that for example.

Using gradle-scalastyle-plugin, I had to add

```groovy
check.dependsOn(scalaStyleCheck)
```

to my `build.gradle` file.

Please make `check` depend on `scalaStyleCheck` once the plugin is applied to a project.

**Comment by olisikh** [comment]
I personally run the scalastyle check right before compiling my sources, e.g. 

```groovy
compileScala.dependsOn(scalaStyleCheck)
```

IMO adding a dependency on scalastyle task is easier then removing it if you don't want it.

Not really convinced it's better to make check depending on it.

**Comment by Flowdalic** [comment]
Having to explicitly specify the dependency breaks gradle's (excellent IMHO) ["convention over configuration" design principle](https://guides.gradle.org/designing-gradle-plugins/).

Unrelated to the discussion: One would *not* usually couple Checkstyle/Bug Hunting checks with the compile task. As those are different aspects of the software and the reason Gradle has them split into the 'assemble' and 'check' tasks.

**Comment by olisikh** [comment]
Ok, didn't know about 'assemble', this actually makes sense. Indeed hooking into assemble fits better than making compileScala depending on scalaStyleCheck.

**Comment by Flowdalic** [comment]
> hooking into assemble

One would expect for something like Scala checkstyle to "hook into" the 'check' task instead. 'Assemble' bulds/compiles the project, 'check' runs the test suite, bug hunting software and checkstyle-like checks. Sorry if this wasn't clear in my previous post.

**Comment by olisikh** [comment]
No, no I got your point, however I want my build to fail without even compiling my sources if Scalastyle found any problems with the source code. 
So 'check' doesn't really fit for my use case. 
But I agree this is probably not common.

**Comment by Flowdalic** [comment]
> So 'check' doesn't really fit for my use case.

I don't think so: 'check' usually depends on 'assemble'.
