### ISSUE TITLE
No such property: output 

### ISSUE THREAD

**Issue by ameyadeodikar** [olisikh/gradle-scalastyle-plugin#7]
I get a build error when trying to include the **output** property within scalastyle configuration:

```
scalastyle {
    config = file("config/scalaStyle/scalaStyle.xml")
    output = file("config/scalaStyle/scalaStyle_results.xml")
    failOnWarning = true
}
```

ERROR:
```
No such property: output for class: org.github.alisiikh.scalastyle.Scalastyle
```
dependency: "com.github.alisiikh:gradle-scalastyle-plugin:3.0.0"

**Comment by olisikh** [comment]
Output is provided per sourceSet, usually you have more than one, so it doesn't make sense to have a global output property.
Use can define an output per sourceSet, the default output is:
```
"${project.buildDir}/scalastyle/${sourceSet.name}/scalastyle-check.xml"
```

I will update the README
